- name: Make directory for cloud-init files
  ansible.builtin.file:
    path: "{{storage_path}}/{{ vm_name }}"
    state: directory
    mode: '0755'
  become: true

- name: Render user-data
  ansible.builtin.template:
    src: user-data.j2
    dest: "{{storage_path}}/{{ vm_name }}/user-data"
    mode: '0644'
  become: true

- name: Render meta-data
  ansible.builtin.template:
    src: meta-data.j2
    dest: "{{storage_path}}/{{ vm_name }}/meta-data"
    mode: '0644'
  become: true

- name: Generate cloud-init seed ISO
  ansible.builtin.command:
    cmd: >
      genisoimage -output {{storage_path}}/{{ vm_name }}/seed.iso
        -volid cidata -joliet -rock
        {{storage_path}}/{{ vm_name }}/user-data
        {{storage_path}}/{{ vm_name }}/meta-data
  args:
    creates: "{{storage_path}}/{{ vm_name }}/seed.iso"
  become: true
