
## Example Playbook to Create 3 VMs
---
- name: Create multiple virtual machines
  hosts: 127.0.0.1
  become: true
  vars_files:
    - ../vars/vm_specs.yml

  tasks:
    - name: Create virtual machines
      include_role:
        name: ../roles/vmcreation
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"
