
## Example Playbook to Create 3 VMs
---
- name: Create multiple virtual machines
  hosts: hypervisor
  vars_files:
    - vars/vm_specs.yml

  tasks:
    - name: Create virtual machines
      include_role:
        name: vmcreation